name: Build Windows installers

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  APP_NAME: ElectronApp
  APP_VERSION: 36.5.0

jobs:
  build-windows:
    name: Build Windows (matrix)
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [ ia32, x64 ]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build for ${{ matrix.arch }}
        run: npx electron-builder --win --${{ matrix.arch }} --publish never
      - name: Rename EXE
        run: Move-Item "dist/${{ env.APP_NAME }} Setup ${{ env.APP_VERSION }}.exe" "dist/${{ env.APP_NAME }} Setup ${{ env.APP_VERSION }}-${{ matrix.arch }}.exe"
      - name: Upload Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload electron-app "dist/${{ env.APP_NAME }} Setup ${{ env.APP_VERSION }}-${{ matrix.arch }}.exe"

      # - name: Upload installer artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: windows-installer-${{ matrix.arch }}
      #     path: dist/*

      