name: Build Windows installers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    name: Build Windows (matrix)
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [ ia32, x64 ]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build for ${{ matrix.arch }}
        run: npx electron-builder --win --${{ matrix.arch }} --publish never

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer-${{ matrix.arch }}
          path: dist/*