name: Build Windows installers

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  APP_NAME: ElectronApp
  APP_VERSION: 36.5.0

jobs:
  build-windows:
    name: Build Windows (matrix)
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [ ia32, x64 ]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'


      - name: Rename Product
        run: |
          $packageJson = Get-Content package.json | ConvertFrom-Json
          $packageJson.build.appId = "com.cic-bot.electron-app.${{ matrix.arch }}"
          $packageJson.build.productName = "ElectronApp${{ matrix.arch }}"
          $packageJson | ConvertTo-Json -Depth 10 | Set-Content package.json
          
          # Verify the change
          Get-Content package.json | Select-String "productName"
          Get-Content package.json | Select-String "appId"

      - name: Install dependencies
        run: npm ci

      - name: Build for ${{ matrix.arch }}
        run: npx electron-builder --win --${{ matrix.arch }} --publish never
      - name: Rename EXE
        run: Move-Item "dist/${{ env.APP_NAME }}${{ matrix.arch }} Setup ${{ env.APP_VERSION }}.exe" "dist/${{ env.APP_NAME }}${{ matrix.arch }}-Setup-${{ env.APP_VERSION }}.exe"
      - name: Upload Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload electron-app "dist/${{ env.APP_NAME }}${{ matrix.arch }}-Setup-${{ env.APP_VERSION }}.exe"
